### ISSUE TITLE
Docs are missing instructions for installing hyperstate package

### ISSUE THREAD

**Issue by sleepwalker2017** [cswinter/hyperstate#7]
pip install pyron won't fix this.
The right solution is to run pip install python-ron

**Comment by cswinter** [comment]
How did you run into this? The [pyproject.toml](https://github.com/cswinter/hyperstate/blob/c3c8c14662fd65280812db7f18a379478da265a2/pyproject.toml#L16) specifies python-ron as a dependency, and that's what it installs for me when I run `pip install hyperstate`.

**Comment by sleepwalker2017** [comment]
> How did you run into this? The [pyproject.toml](https://github.com/cswinter/hyperstate/blob/c3c8c14662fd65280812db7f18a379478da265a2/pyproject.toml#L16) specifies python-ron as a dependency, and that's what it installs for me when I run `pip install hyperstate`.

sorry, I'm new with python. I didn't realize that the repo can be installed with that command.

**Comment by sleepwalker2017** [comment]
> How did you run into this? The [pyproject.toml](https://github.com/cswinter/hyperstate/blob/c3c8c14662fd65280812db7f18a379478da265a2/pyproject.toml#L16) specifies python-ron as a dependency, and that's what it installs for me when I run `pip install hyperstate`.

I run this  and it works fine.

**Comment by cswinter** [comment]
I mean if you ran into it someone else will too. Looks like a bug in the docs to me, they should be mentioning how to install the library.

**Comment by sleepwalker2017** [comment]
Actually, I didn't see a docs saying how to install the package. I just see the Readme first, and try to run the demo in the project directory.

**Comment by cswinter** [comment]
Fixed in https://github.com/cswinter/hyperstate/commit/9125a5a61425dde1bdd42e501c40cfc65a5f2fc9
